# Generated by Django 5.2.7 on 2025-10-30 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Профиль клиента', 'verbose_name_plural': 'Профили клиентов'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='serviceinterest',
            options={'ordering': ['client', 'service_name'], 'verbose_name': 'Интерес к услуге', 'verbose_name_plural': 'Интересы к услугам'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date'], 'verbose_name': 'Визит', 'verbose_name_plural': 'Визиты'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='№ квартиры'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='current_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текущий провайдер'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Портрет клиента, например: мужчина 40 лет, безработный', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='fair_price',
            field=models.CharField(blank=True, max_length=50, verbose_name='Справедливая цена'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='interested_services',
            field=models.CharField(blank=True, help_text='Какие услуги интересуют', max_length=255, verbose_name='Интересующие услуги'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='rost.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='preferred_contact_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Удобное время для связи'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='satisfaction_level',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Оценка текущего провайдера (1-5)', null=True, verbose_name='Уровень удовлетворенности'),
        ),
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='object',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='rost.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='object',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='object',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='serviceinterest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='rost.clientprofile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='serviceinterest',
            name='interested',
            field=models.BooleanField(default=False, verbose_name='Заинтересован'),
        ),
        migrations.AlterField(
            model_name='serviceinterest',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('engineer', 'Инженер'), ('supervisor', 'Супервайзер')], default='engineer', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='rost.clientprofile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата визита'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Инженер'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='gps_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_synced',
            field=models.BooleanField(default=True, help_text='Синхронизировано ли с сервером', verbose_name='Синхронизировано'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceinterest',
            unique_together={('client', 'service_name')},
        ),
    ]
