# Generated by Django 5.2.7 on 2025-10-30 08:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rost', '0002_alter_city_options_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер квартиры/помещения'),
        ),
        migrations.AddField(
            model_name='object',
            name='client_portrait',
            field=models.TextField(blank=True, help_text='Например: мужчина 40 лет, безработный', null=True, verbose_name='Описание портрета клиента'),
        ),
        migrations.AddField(
            model_name='object',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='object',
            name='convenient_contact_time',
            field=models.CharField(blank=True, choices=[('morning', 'Утро (9:00-12:00)'), ('lunch', 'Обед (12:00-15:00)'), ('evening', 'Вечер (15:00-18:00)'), ('late_evening', 'Поздний вечер (18:00-21:00)'), ('weekend', 'Выходные дни'), ('any', 'Любое время')], max_length=20, null=True, verbose_name='Удобное время для связи'),
        ),
        migrations.AddField(
            model_name='object',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AddField(
            model_name='object',
            name='current_provider_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Очень неудовлетворен'), (2, '2 - Неудовлетворен'), (3, '3 - Нейтрален'), (4, '4 - Удовлетворен'), (5, '5 - Очень удовлетворен')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка текущего провайдера'),
        ),
        migrations.AddField(
            model_name='object',
            name='desired_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Рублей в месяц', max_digits=8, null=True, verbose_name='Желаемая цена за интернет'),
        ),
        migrations.AddField(
            model_name='object',
            name='interested_services',
            field=models.JSONField(blank=True, help_text='Какие услуги интересуют клиента', null=True, verbose_name='Интерес к услугам'),
        ),
        migrations.AddField(
            model_name='object',
            name='next_contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего контакта'),
        ),
        migrations.AddField(
            model_name='object',
            name='notes',
            field=models.TextField(blank=True, help_text='Произвольный комментарий инженера', null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='object',
            name='services_used',
            field=models.JSONField(blank=True, help_text='Выберите используемые услуги', null=True, verbose_name='Чем пользуется'),
        ),
        migrations.AddField(
            model_name='object',
            name='status',
            field=models.CharField(choices=[('new', 'Новый клиент'), ('potential', 'Потенциальный клиент'), ('existing', 'Существующий клиент'), ('refused', 'Отказался'), ('callback', 'Нужен перезвон')], default='new', max_length=20, verbose_name='Статус клиента'),
        ),
        migrations.AddField(
            model_name='object',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='object',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_objects', to='rost.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название объекта'),
        ),
    ]
