# Generated by Django 5.2.7 on 2025-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rost', '0003_object_apartment_number_object_client_portrait_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='desired_price',
            field=models.PositiveIntegerField(blank=True, help_text='Рублей в месяц', null=True, verbose_name='Желаемая цена за интернет'),
        ),
    ]
