# Generated by Django 5.2.7 on 2025-10-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rost', '0004_alter_object_desired_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
